# Generated by Django 5.1.5 on 2025-02-04 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrdersItem',
            new_name='OrderItem',
        ),
    ]
